In [ ]:
import array
arr = array.array('I',[2,3,4,5,6,7,8,9])
print("New created array.",end="")
for i in range (0,5):
  print (arr[i],end="")
  print('\r')

New created array.2
3
4
5
6


In [ ]:
import pandas as pd
dict = {'Name':["Neha","Puja","Sakshi","Keya"],'Age':["18","19","20","17"]}
info = pd.DataFrame(dict, index=[201,202,203,204])
print(info)


       Name Age
201    Neha  18
202    Puja  19
203  Sakshi  20
204    Keya  17


In [ ]:
import pandas as pd
dict = {'Name':["Neha","Puja","Sakshi","Keya"],'Age':["18","19","20","17"]}
info = pd.DataFrame(dict, index=[201,202,201,204])
print(info.loc[201])

       Name Age
201    Neha  18
201  Sakshi  20


In [ ]:
import numpy as np
arr = np.arange(16)
print ("Original array is :\n",arr)
arr = np.arange(16).reshape(4,4)
print ("Reshaped array is :\n",arr)

Original array is :
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Reshaped array is :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [ ]:
import numpy as np
a = np.array([1,2,3])
print(type(a),"\n")
print(a.shape)
print(a[0],a[1],a[2],"\n")
a[0] = 5
print(a,"\n")
b = np.array([[1,2,3],[4,5,6]])
print(b.shape)
print(b[0,0],b[0,1],b[1,0],"\n")

a = np.zeros((2,2))
print(a,"\n")

b = np.ones((1,2))
print(b,"\n")

c = np.full((2,2),7)
print(c,"\n")

d = np.eye(2)
print(d,"\n")

e = np.random.random((2,2))
print(e)

<class 'numpy.ndarray'> 

(3,)
1 2 3 

[5 2 3] 

(2, 3)
1 2 4 

[[0. 0.]
 [0. 0.]] 

[[1. 1.]] 

[[7 7]
 [7 7]] 

[[1. 0.]
 [0. 1.]] 

[[0.3022461  0.96896422]
 [0.12552725 0.43283205]]


In [ ]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b = a[:2, 1:3]
print (a[0,1])
b[0,0] = 77
print (a[0,1])


2
77


In [ ]:
import numpy as np
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
r1 = a[1, :]
r2 = a[1:2, :]
print(r1,r1.shape)
print(r2,r2.shape,"\n")
c1 = a[: ,1]
c2 = a[: ,1:2]
print(c1,"\t",c1.shape,"\n")
print(c2,c2.shape,"\n")


[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4) 

[ 2  6 10] 	 (3,) 

[[ 2]
 [ 6]
 [10]] (3, 1) 



In [ ]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
print(a[[0,1,2],[0,1,0]],"\n")
print(np.array([a[0,0],a[1,1],a[2,0]]),"\n")
print(a[[0,0],[1,1]],"\n")
print(np.array([a[0,1],a[0,1]]),"\n")


[1 4 5] 

[1 4 5] 

[2 2] 



In [2]:
import numpy as np
a = np.array([[1,2],[3,4],[5,6]])
idx = (a > 2)
print(idx,"\n")
print(a[idx],"\n")
print(a[a>2],"\n")

[[False False]
 [ True  True]
 [ True  True]] 

[3 4 5 6] 

[3 4 5 6] 



In [5]:
import numpy as np
x = np.array([1,2])
print(x.dtype,"\n")
x = np.array([1.5,2.5])
print(x.dtype,"\n")
x = np.array([1,2],dtype=np.int64)
print(x.dtype)

int64 

float64 

int64
